/**
 * Unified Supabase Database type definitions.
 * Single source of truth for all database types — generated by:
 *   npx supabase gen types --project-id <PROJECT_ID>
 *
 * All application types are derived from these via the Row<T>/Insert<T>/Update<T> helpers.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string;
          display_name: string | null;
          avatar_url: string | null;
          xp: number;
          level: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          username: string;
          display_name?: string | null;
          avatar_url?: string | null;
          xp?: number;
          level?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          username?: string;
          display_name?: string | null;
          avatar_url?: string | null;
          xp?: number;
          level?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      projects: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          status: 'draft' | 'active' | 'completed' | 'archived';
          user_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          status?: 'draft' | 'active' | 'completed' | 'archived';
          user_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string | null;
          status?: 'draft' | 'active' | 'completed' | 'archived';
          user_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      badges: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          icon_url: string | null;
          xp_reward: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          icon_url?: string | null;
          xp_reward?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          icon_url?: string | null;
          xp_reward?: number;
          created_at?: string;
        };
      };
      user_badges: {
        Row: {
          id: string;
          user_id: string;
          badge_id: string;
          earned_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          badge_id: string;
          earned_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          badge_id?: string;
          earned_at?: string;
        };
      };
      stages: {
        Row: {
          id: string;
          project_id: string;
          title: string;
          order_index: number;
          xp_reward: number;
          completed_by: string[] | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          title: string;
          order_index: number;
          xp_reward?: number;
          completed_by?: string[] | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          title?: string;
          order_index?: number;
          xp_reward?: number;
          completed_by?: string[] | null;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      project_status: 'draft' | 'active' | 'completed' | 'archived';
    };
  };
}

/** Convenience helpers for deriving row types from the Database definition. */
export type Tables = Database['public']['Tables'];
export type Row<T extends keyof Tables> = Tables[T]['Row'];
export type Insert<T extends keyof Tables> = Tables[T]['Insert'];
export type Update<T extends keyof Tables> = Tables[T]['Update'];

/** Concrete row types used throughout the application. */
export type Profile = Row<'profiles'>;
export type Project = Row<'projects'>;
export type Badge = Row<'badges'>;
export type UserBadge = Row<'user_badges'>;
export type Stage = Row<'stages'>;

/** Concrete insert types (omit auto-generated fields like id and created_at). */
export type ProfileInsert = Insert<'profiles'>;
export type ProjectInsert = Insert<'projects'>;
export type BadgeInsert = Insert<'badges'>;
export type UserBadgeInsert = Insert<'user_badges'>;
export type StageInsert = Insert<'stages'>;

/** Concrete update types (all fields optional). */
export type ProfileUpdate = Update<'profiles'>;
export type ProjectUpdate = Update<'projects'>;
export type BadgeUpdate = Update<'badges'>;
export type UserBadgeUpdate = Update<'user_badges'>;
export type StageUpdate = Update<'stages'>;
